### ISSUE TITLE
Error building locally

### ISSUE THREAD

**Issue by sisirkoppaka** [jonathantompson/torchzlib#2]
Having the following issue when I do a luarocks make with the rockspec path locally.
# 

Scanning dependencies of target torchzlib
[ 94%] Building C object CMakeFiles/torchzlib.dir/torchzlib.c.o
In file included from /Users/sisirkoppaka/torchzlib/torchzlib.c:20:
In file included from generic/torchzlib.c:2:
In file included from /Users/sisirkoppaka/torchzlib/generic/torchzlib.c:19:
/Users/sisirkoppaka/torchzlib/zlib/zlib.h:86:5: error: unknown type name 'z_const'; did you mean 'const'?
    z_const Bytef _next_in;     /_ next input byte _/
    ^~~~~~~
    const
/Users/sisirkoppaka/torchzlib/zlib/zlib.h:94:5: error: unknown type name 'z_const'; did you mean 'const'?
    z_const char *msg;  /_ last error message, NULL if no error _/
    ^~~~~~~
    const
/Users/sisirkoppaka/torchzlib/zlib/zlib.h:1026:33: error: unknown type name 'z_const'; did you mean 'const'?
                                z_const unsigned char FAR \* FAR *));
                                ^~~~~~~
                                const
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/zconf.h:240:23: note: expanded from macro 'OF'
 define OF(args)  args
                      ^
In file included from /Users/sisirkoppaka/torchzlib/torchzlib.c:20:
In file included from generic/torchzlib.c:2:
In file included from /Users/sisirkoppaka/torchzlib/generic/torchzlib.c:19:
/Users/sisirkoppaka/torchzlib/zlib/zlib.h:1349:31: error: expected ';' after top level declarator
ZEXTERN int ZEXPORTVA gzprintf Z_ARG((gzFile file, const char *format, ...));
                              ^
                              ;
/Users/sisirkoppaka/torchzlib/zlib/zlib.h:1748:15: error: unknown type name 'z_crc_t'
ZEXTERN const z_crc_t FAR \* ZEXPORT get_crc_table    OF((void));
              ^
/Users/sisirkoppaka/torchzlib/zlib/zlib.h:1758:43: error: expected ';' after top level declarator
ZEXTERN int            ZEXPORTVA gzvprintf Z_ARG((gzFile file,
                                          ^
                                          ;
6 errors generated.
make[2]: *_\* [CMakeFiles/torchzlib.dir/torchzlib.c.o] Error 1
make[1]: **\* [CMakeFiles/torchzlib.dir/all] Error 2
make: **\* [all] Error 2

Error: Build error: Failed building.

**Comment by deltheil** [comment]
It sounds like it's enough to replace `#include "zlib/zlib.h"` by `#include "zlib.h"` [here](https://github.com/jonathantompson/torchzlib/blob/0e987922f46306c0dc0197f7c6df87c4a6f0b1df/generic/torchzlib.c#L19) (since both headers are installed under an ad hoc torch sub dir [here](https://github.com/jonathantompson/torchzlib/blob/0e987922f46306c0dc0197f7c6df87c4a6f0b1df/zlib/CMakeLists.txt#L79-L80)). But I let CMake experts confirm it's the right thing to do :)

_Another thing: doing `luarocks remove torchzlib` should also remove `zlib.h` and `zconf.h` from `~/torch/install/include` and `libzlib.so` from `~/torch/install/lib/`, right?_

**Comment by deltheil** [comment]
Well I was wrong: what's really missing here is the path to `build/zlib/zconf.h`. I sent a PR (#3).

**Comment by jonathantompson** [comment]
Thanks again @deltheil!
