### ISSUE TITLE
require 'torchzlib' returns true

### ISSUE THREAD

**Issue by kconor** [jonathantompson/torchzlib#5]
It would be helpful if it returned torchzlib so "local tz = require 'torchzlib'" would work properly.

**Comment by jonathantompson** [comment]
Thanks Kevin! Feel free to submit a PR with the change and I'll merge it,
otherwise I'll get around to it in a few days (currently on paternity
leave).

**Comment by soumith** [comment]
@kconor since torchzlib doesn't return any functions itself (but writes into the "torch" global table), it doesn't make sense

**Comment by jonathantompson** [comment]
Ahh yeah, good point @soumith.

@soumith you're so smart :-)

I'll close this.  @kconor, can you check to make sure torch.CompressedTensor exists after loading the library?
